[package]
name = "just-uninstall"
version = "0.1.0"
authors = ["Randy Sch√ºtt <rswhite4@googlemail.com>"]
edition = "2018"

[dependencies]
just-core = { git = "https://github.com/just-cli/just-core" }
structopt = "0.2.14"
semver= "0.9"
log = "0.4.6"